window.PRODUCTS_LOCAL = [
  /* ── AÇAÍ ── */
  {
    id: 1, cat: 'acai',
    name: 'Açaí 300ml',
    desc: 'Açaí de 300ml com leite em pó e leite condensado',
    price: 25.00,
    img: 'https://tse4.mm.bing.net/th/id/OIP.SADHoFyzV3n_a67qeGZ_4gHaHa?w=1800&h=1800&rs=1&pid=ImgDetMain&o=7&rm=3',
    badges: [],
  },
  {
    id: 2, cat: 'acai',
    name: 'Açaí 500ml',
    desc: 'Açaí cremoso e geladinho para qualquer hora',
    price: 30.00,
    img: 'https://static-images.ifood.com.br/pratos/aaf06696-490e-41fd-b22f-d24d20697363/202404291400_5845_i.jpg',
    badges: ['mais'],
  },
  {
    id: 3, cat: 'acai',
    name: 'Combo Açaí 500ml',
    desc: 'Combo mais pedido: Açaí 500ml com 3 adicionais grátis',
    price: 35.00,
    img: 'https://alphagel.com.br/wp-content/uploads/2022/04/post_thumbnail-a4af202467328269ce55eb0921bfd1d9.jpeg',
    badges: ['combo'],
  },
  {
    id: 47, cat: 'combos',
    name: 'Combo Promo',
    desc: 'X-Burger + batata por preço especial, só hoje',
    price: 29.99,
    img: "images/combo-promo.png",
    fallbackIcon: 'fa-tags',
    fallbackLabel: 'Promo',
    badges: ['novo'],
  },
  {
    id: 48, cat: 'combos',
    name: 'Combo Família',
    desc: 'Combo completo para dividir com a família',
    price: 120.00,
    img: 'https://img.magnific.com/premium-photo/tray-burgers-fries_1099965-40358.jpg',
    badges: ['dest'],
  },
  {
    id: 49, cat: 'combos',
    name: 'Combo Casal',
    desc: 'Combo perfeito para duas pessoas',
    price: 90.00,
    img: 'https://static.vecteezy.com/system/resources/previews/026/794/680/large_2x/double-hamburger-isolated-on-white-background-fresh-burger-fast-food-with-beef-and-cream-cheese-realistic-image-ultra-hd-high-design-very-detailed-free-photo.jpg',
    badges: [],
  },
  /* ── ADICIONAIS AÇAÍ (produtos da loja) ── */
  {
    id: 4, cat: 'adicionais',
    name: 'Freegells',
    desc: 'Extra forte e refrescante para qualquer hora',
    price: 2.50,
    img: 'https://paulinhodoces.com.br/wp-content/uploads/2024/02/3-4.jpg',
    badges: ['novo'],
  },
  {
    id: 5, cat: 'adicionais',
    name: 'OREO',
    desc: 'Crocante e irresistível',
    price: 5.00,
    img: 'images/oreo.webp',
    badges: ['mais'],
  },
  {
    id: 6, cat: 'adicionais',
    name: 'Paçoquinha',
    desc: 'O sabor tradicional que todo mundo ama',
    price: 1.00,
    img: 'https://a-static.mlcdn.com.br/800x560/pacoquinha-queridinha-dos-brasil-tradicional/modaestilochequebem/a3f7c1c47ad811eda7574201ac185019/49d3d8f5eddcfe6604494c4a13e33f15.jpeg',
    badges: [],
  },
  {
    id: 7, cat: 'adicionais',
    name: 'Pirulito',
    desc: 'Docinho que alegra qualquer momento',
    price: 0.50,
    img: 'https://segredosdomundo.r7.com/wp-content/uploads/2020/09/pirulito-a-historia-por-tras-do-desenvolvimento-do-doce-em-palito-1-scaled.jpg',
    badges: [],
  },
  /* ── HAMBÚRGUER ── */
  {
    id: 8, cat: 'hamburguer',
    name: 'Burguer Duplo',
    desc: 'Dois hambúrgueres, queijo duplo e lanche reforçado',
    price: 20.00,
    img: 'https://img.magnific.com/fotos-premium/burger-costeleta-dupla-queijo-cheddar-duplo-bacon-cebola-frita-picles-molho-e-pao-artesanal_524291-99.jpg?w=740',
    badges: [],
  },
  {
    id: 9, cat: 'hamburguer',
    name: 'X-Burger',
    desc: 'Hambúrguer clássico, simples e muito saboroso',
    price: 18.00,
    img: 'https://cdn.sanity.io/images/8ngmz6db/production/a8384252d6bce85debd94c3b5b9515aae7e34d7d-1024x1024.webp',
    badges: ['mais'],
  },
  {
    id: 10, cat: 'hamburguer',
    name: 'X-Salada',
    desc: 'Hambúrguer com salada fresca, queijo e molho especial',
    price: 24.00,
    img: 'https://www.montarumnegocio.com/wp-content/uploads/2017/06/Como-fazer-x-Salada-na-chapa-para-vender.jpg',
    badges: [],
  },
  {
    id: 37, cat: 'hamburguer',
    name: 'X-Tudo',
    desc: 'Hambúrguer super recheado, completo e bem servido',
    price: 90.00,
    img: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/aa/72/3b/todoterreno.jpg?w=400&h=-1&s=1',
    badges: ['dest'],
  },
  {
    id: 38, cat: 'hamburguer',
    name: 'X-Frango',
    desc: 'Hambúrguer de frango saboroso e bem montado',
    price: 32.00,
    img: 'https://static.vecteezy.com/system/resources/thumbnails/029/839/218/small_2x/double-hamburger-isolated-on-black-background-ai-generative-photo.jpg',
    badges: [],
  },
  {
    id: 39, cat: 'hamburguer',
    name: 'X-Egg',
    desc: 'Hambúrguer com ovo, queijo e acompanhamentos especiais',
    price: 28.00,
    img: 'https://img.freepik.com/fotos-premium/um-hamburguer-com-um-ovo-frito_900321-27508.jpg',
    badges: [],
  },
  {
    id: 40, cat: 'hamburguer',
    name: 'X-Coração',
    desc: 'Lanche especial com coração, bacon e muito sabor',
    price: 35.00,
    img: 'https://www.fastburguerx.com.br/public/files/produtos/fast-x-coracao-com-bacon-964-3142.webp',
    badges: [],
  },
  {
    id: 41, cat: 'hamburguer',
    name: 'X-Calabresa',
    desc: 'Hambúrguer com calabresa, queijo e molho marcante',
    price: 32.00,
    img: 'https://i.pinimg.com/originals/8c/16/16/8c1616fcbac07e42db01f61cb5190180.jpg',
    badges: [],
  },
  {
    id: 42, cat: 'hamburguer',
    name: 'X-Alcatra',
    desc: 'Hambúrguer premium de alcatra com muito sabor',
    price: 38.00,
    img: 'https://minervafoods.com/wp-content/uploads/2023/09/HamburguerAlcatraComBacon_1-1920x1274.jpg',
    badges: [],
  },
  /* ── ARTESANAIS ── */
  {
    id: 11, cat: 'artesanais',
    name: 'X-Bacon',
    desc: 'Hambúrguer artesanal com bacon crocante',
    price: 32.00,
    img: 'https://icookfortwo.com/wp-content/uploads/2022/06/featured-peanut-butter-bacon-burger-768x512.jpg',
    badges: ['dest'],
  },
  {
    id: 50, cat: 'artesanais',
    name: 'X Egg Artesanal',
    desc: 'Artesanal com ovo, queijo e muito sabor',
    price: 35.00,
    img: 'https://img.magnific.com/premium-photo/cheeseburger-with-crispy-fried-egg_1179130-129084.jpg',
    badges: [],
  },
  {
    id: 51, cat: 'artesanais',
    name: 'Top Burger Cheddar',
    desc: 'Pão, burger com carne bovina, queijo cheddar e fritas',
    price: 35.00,
    img: 'https://cdn.mer-cat.com/cheddarsburger/400x400/img/product/classic_1692680374I1qp4L.jpg?pass=eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjoiNDAweDQwMC9pbWcvcHJvZHVjdC9jbGFzc2ljXzE2OTI2ODAzNzRJMXFwNEwuanBnIn0.KcW577fdbWgfM5nPH91sLNdN4jGt__G7FbG12SABg1E',
    badges: [],
  },
  {
    id: 52, cat: 'artesanais',
    name: 'Big Picanha',
    desc: 'Pão, tomate, alface, burger bovino, picanha fatiada 150g, queijo, molho especial e fritas',
    price: 56.00,
    img: 'https://minervafoods.com/wp-content/uploads/2022/12/burguer-de-picanha.jpg',
    badges: ['dest'],
  },
  {
    id: 53, cat: 'artesanais',
    name: 'Big Classic',
    desc: 'Hambúrguer artesanal clássico com queijo, salada e molho especial',
    price: 38.00,
    img: 'https://saudelab.com/wp-content/uploads/2023/02/hamburguer-caseiro-artesanal.jpg',
    badges: [],
  },
  {
    id: 54, cat: 'artesanais',
    name: 'Big Calabresa',
    desc: 'Hambúrguer artesanal com calabresa, queijo e molho especial',
    price: 40.00,
    img: 'https://static-images.ifood.com.br/pratos/ddbb1ad7-e3e8-49bc-8afe-fea17bf84b5f/202411031750_K5WP_i.jpg',
    badges: [],
  },
  {
    id: 55, cat: 'artesanais',
    name: 'Big Bacon',
    desc: 'Hambúrguer artesanal com bacon crocante, queijo e molho especial',
    price: 40.00,
    img: 'https://www.fullerssugarhouse.com/wp-content/uploads/2021/08/maplebaconburger.jpg',
    badges: [],
  },
  /* ── HOT DOGS ── */
  {
    id: 12, cat: 'hotdog',
    name: 'Hot Dog Simples',
    desc: 'Cachorro-quente tradicional, completo e saboroso',
    price: 20.00,
    img: 'https://www.comidaereceitas.com.br/wp-content/uploads/2019/06/Cachorro-quente-completo-freepik-780x520.jpg',
    badges: [],
  },
  {
    id: 13, cat: 'hotdog',
    name: 'Hot Dog Bacon',
    desc: 'Hot dog caprichado com bacon crocante e molho especial',
    price: 28.00,
    img: 'https://receitasbr.com.br/wp-content/uploads/2023/06/cachorro-quente-com-bacon.jpg',
    badges: ['novo'],
  },
  {
    id: 34, cat: 'hotdog',
    name: 'Hot Dog Calabresa',
    desc: 'Hot dog com calabresa acebolada e muito sabor',
    price: 28.00,
    img: 'https://s2.glbimg.com/1xoFGeFPFrMqqeE2yufX5EFSe0c=/1200x/smart/filters:cover():strip_icc()/i.s3.glbimg.com/v1/AUTH_1f540e0b94d8437dbbc39d567a1dee68/internal_photos/bs/2021/7/w/YNR7wZQEGsRUDdJ9OvhQ/cachorro-quente-de-calabresa-acebolada.jpg',
    badges: [],
  },
  {
    id: 35, cat: 'hotdog',
    name: 'Hot Dog Duplo',
    desc: 'Dois sabores em um lanche reforçado e bem recheado',
    price: 22.00,
    img: 'https://img.magnific.com/fotos-premium/cachorro-quente-com-salsicha-grande-recheada-com-maionese-derretida-e-uma-pitada-de-verduras-picadas_358001-22843.jpg',
    badges: [],
  },
  {
    id: 36, cat: 'hotdog',
    name: 'Hot Dog Frango',
    desc: 'Hot dog com frango cremoso, molhos e acompanhamentos',
    price: 29.00,
    img: 'https://imagens.imirante.com.br/imagens/noticias/2023/12/26/VMWgzaAS96O9BGbuCr5dqJ8jPsYzhk3wLMBkmPaN.png?w=896&h=448&crop=538%2C+269%2C+0%2C+39.5&fit=crop&s=9db2068290bfcbb5652c1b84952f901d',
    badges: [],
  },
  /* ── PORÇÕES ── */
  {
    id: 14, cat: 'porcoes',
    name: 'Fritas 500g',
    desc: 'Porção de batata frita crocante e dourada',
    price: 32.00,
    img: 'https://www.cenariomt.com.br/wp-content/uploads/2023/04/como-fazer-batata-frita-na-airfryer-1024x576.jpg',
    badges: ['mais'],
  },
  {
    id: 15, cat: 'porcoes',
    name: 'Fritas com Bacon e Cheddar',
    desc: 'Fritas com cheddar cremoso e bacon crocante',
    price: 49.00,
    img: 'https://img.magnific.com/fotos-premium/lanche-hd-8k-papel-de-parede-imagem-fotografica_890746-78783.jpg',
    badges: ['dest'],
  },
  {
    id: 43, cat: 'porcoes',
    name: 'Porção Mista',
    desc: 'Porção completa e bem servida para compartilhar',
    price: 100.00,
    img: 'https://i.pinimg.com/originals/c4/52/85/c45285b431ccf7c033887e8304d95c3c.png',
    badges: [],
  },
  {
    id: 44, cat: 'porcoes',
    name: 'Picanha com Fritas',
    desc: 'Picanha saborosa acompanhada de fritas crocantes',
    price: 140.00,
    img: 'https://3.bp.blogspot.com/-MGV8o-XpXoA/WP4a601kpWI/AAAAAAAAHIs/oe-hhmu-xBk6nKG2_drwsmVG8OAsLZsfwCLcB/s1600/6001_940x582-940x582.jpg',
    badges: ['dest'],
  },
  {
    id: 45, cat: 'porcoes',
    name: 'Fritas e Calabresa',
    desc: 'Batata frita crocante com calabresa acebolada',
    price: 45.00,
    img: 'https://i.pinimg.com/originals/ec/6f/22/ec6f22c945adacc41063e6c90c8d889e.png',
    badges: [],
  },
  {
    id: 46, cat: 'porcoes',
    name: 'Batata com Bacon',
    desc: 'Batata frita com bacon crocante e muito sabor',
    price: 45.00,
    img: 'https://i.pinimg.com/originals/58/b1/a5/58b1a53af1d150d879cd77305487d5da.png',
    badges: [],
  },
  /* ── BEBIDAS ── */
  {
    id: 16, cat: 'bebidas',
    name: 'Coca-Cola 2 Litros',
    desc: 'Gelada, perfeita para acompanhar seu pedido',
    price: 16.00,
    img: 'https://andinacocacola.vtexassets.com/arquivos/ids/158758-800-auto?aspect=true&height=auto&v=639156020671730000&width=800',
    badges: [],
  },
  {
    id: 17, cat: 'bebidas',
    name: 'Água',
    desc: 'Água mineral gelada, perfeita para qualquer momento',
    price: 3.00,
    img: 'https://aguamineralhydrate.com.br/wp-content/uploads/2016/02/Garrafa-Agua-Mineral-500-ml-pacote-12-unidades.jpg',
    badges: [],
  },
  {
    id: 18, cat: 'bebidas',
    name: 'Caipirinha',
    desc: 'Caipirinha artesanal gelada e refrescante',
    price: 20.00,
    img: 'https://cdn.thefreshmancook.com/wp-content/uploads/2024/04/Caipirinha-Recipe-2-1024x1024.jpg',
    badges: [],
  },
  {
    id: 19, cat: 'bebidas',
    name: 'Caixa de Brahma',
    desc: 'Caixa com cervejas Brahma geladas',
    price: 60.00,
    img: 'https://choppbrahmaexpress.vtexassets.com/arquivos/ids/158114-800-auto?v=638410151046000000&width=800&height=auto&aspect=true',
    badges: [],
  },
  {
    id: 20, cat: 'bebidas',
    name: 'Caixa de Kaiser',
    desc: 'Caixa com cervejas Kaiser geladas',
    price: 50.00,
    img: 'https://2.bp.blogspot.com/-3jCrEZl2hjA/V_fDGDiIrQI/AAAAAAABjOg/jMpPn9PaDscn31Do1quhmNGclWpZdGQVACLcB/s1600/kaiser%2B6.jpg',
    badges: [],
  },
  {
    id: 21, cat: 'bebidas',
    name: 'Caixa de Skol',
    desc: 'Caixa com cervejas Skol geladas',
    price: 60.00,
    img: 'https://http2.mlstatic.com/D_NQ_NP_2X_909577-MLB45554443155_042021-F.jpg',
    badges: [],
  },
  {
    id: 22, cat: 'bebidas',
    name: 'Coca-Cola 600ml',
    desc: 'Coca-Cola garrafa 600ml gelada',
    price: 9.00,
    img: 'https://tse3.mm.bing.net/th/id/OIP.AvYbB6jhJxGC_SCus4CpwwHaHa?w=2847&h=2847&rs=1&pid=ImgDetMain&o=7&rm=3',
    badges: [],
  },
  {
    id: 23, cat: 'bebidas',
    name: 'Coca-Cola Lata',
    desc: 'Coca-Cola lata 350ml gelada',
    price: 6.00,
    img: 'https://static.vecteezy.com/system/resources/previews/047/280/244/non_2x/a-can-of-coca-cola-on-a-white-background-free-photo.jpg',
    badges: [],
  },
  {
    id: 24, cat: 'bebidas',
    name: 'Copão',
    desc: 'Whisky, gin, vodka e muitos outros drinks',
    price: 25.00,
    img: 'images/copao.jpg',
    badges: [],
  },
  {
    id: 25, cat: 'bebidas',
    name: 'Del Valle',
    desc: 'Suco Del Valle gelado, vários sabores',
    price: 7.00,
    img: 'https://andinacocacola.vtexassets.com/arquivos/ids/158622-800-auto?aspect=true&height=auto&v=639094449084230000&width=800',
    badges: [],
  },
  {
    id: 26, cat: 'bebidas',
    name: 'Guaraná',
    desc: 'Guaraná Antarctica gelado e refrescante',
    price: 6.00,
    img: 'https://drogariacristina.com.br/BACKOFFICE/Uploads/Produto/Normal/7891991000826.jpg',
    badges: [],
  },
  {
    id: 27, cat: 'bebidas',
    name: 'Kaiser',
    desc: 'Cerveja Kaiser lata 350ml gelada',
    price: 6.00,
    img: 'https://cdn.irmaospatrocinio.com.br/img/p/1/6/8/9/5/4/168954-thickbox_default.jpg',
    badges: [],
  },
  {
    id: 28, cat: 'bebidas',
    name: 'Mini Coca',
    desc: 'Coca-Cola mini 250ml gelada',
    price: 3.00,
    img: 'https://www.sanmiguelchapultepec.shop/wp-content/uploads/2020/04/coca-cola-mini-250-ml.jpg',
    badges: [],
  },
  {
    id: 29, cat: 'bebidas',
    name: 'Red Bull',
    desc: 'Red Bull energético 250ml',
    price: 15.00,
    img: 'https://barcodelive.org/filemanager/data-images/imgs/20230223/News_10%20Best%20Red%20Bull%20Flavors%20You%20Should%20Try_2.jpg',
    badges: [],
  },
  {
    id: 30, cat: 'bebidas',
    name: 'Skol Lata',
    desc: 'Cerveja Skol lata 350ml gelada',
    price: 7.00,
    img: 'https://a-static.mlcdn.com.br/800x560/cerveja-skol-lata-caixa-com-12/bartropical/9479d15413fb11ed853c4201ac185079/dd3eccaf4fa30803d455dd28510aad07.jpg',
    badges: [],
  },
  {
    id: 31, cat: 'bebidas',
    name: 'Brahma',
    desc: 'Cerveja Brahma lata 350ml gelada',
    price: 7.00,
    img: 'https://choppbrahmaexpress.vtexassets.com/arquivos/ids/155702/brahma-lata-350ml.jpg?v=637353454674430000',
    badges: [],
  },
  {
    id: 32, cat: 'bebidas',
    name: 'Heineken',
    desc: 'Cerveja Heineken 330ml gelada',
    price: 12.00,
    img: 'https://jamaicagetawaytravels.com/wp-content/uploads/2020/06/Heineken.jpg',
    badges: ['mais'],
  },
  {
    id: 33, cat: 'bebidas',
    name: 'Heineken Zero',
    desc: 'Heineken Zero Álcool 330ml',
    price: 7.00,
    img: 'https://penielvicfalls.com/wp-content/uploads/2024/09/Heineken-zero-1024x1024.jpeg',
    badges: [],
  },
  /* ── SALGADINHOS ── */
  {
    id: 56, cat: 'salgadinhos',
    name: 'Salgadinho Quero S. Mais',
    desc: 'Salgadinho crocante para acompanhar seu pedido',
    price: 2.50,
    img: 'https://ac9d37e35c0a3dbcbeefb2c0db18e07b.cdn.bubble.io/f1726700761916x375871732471283000/SalgadosHero.webp?ignore_imgix',
    badges: [],
  },
  {
    id: 57, cat: 'salgadinhos',
    name: 'Salgadinho Nacho',
    desc: 'Nachos crocantes e cheios de sabor',
    price: 5.00,
    img: 'https://static.itdg.com.br/images/auto-auto/258b003211e5e4925693b5dfac1d6ca6/nachos-4-ingredientes.jpg',
    badges: [],
  },
  {
    id: 58, cat: 'salgadinhos',
    name: 'Salgadinho Batata',
    desc: 'Salgadinho sabor batata, crocante e saboroso',
    price: 5.00,
    img: 'https://paulistaoatacadista.vtexassets.com/arquivos/ids/377999/SalgadinhoBatataLaysClassica70g1.jpg?v=638469844938770000',
    badges: [],
  },
  {
    id: 59, cat: 'salgadinhos',
    name: 'Salgadinho Bacon',
    desc: 'Salgadinho sabor bacon, perfeito para beliscar',
    price: 5.00,
    img: 'https://d21wiczbqxib04.cloudfront.net/w4q2-fCq48EEKLo9GFSi45JRXx8=/fit-in/600x0/filters:fill(FFFFFF):background_color(white)/https://osuper-ecommerce-koch.s3.sa-east-1.amazonaws.com/bb49cb09-SalgadinhodeBaconNabeli100G_69318.jpeg',
    badges: [],
  },
];
